export const LOAD_CART = '@SC/LOAD_CART';
export const ADD_PRODUCT = '@SC/ADD_PRODUCT';
export const REMOVE_PRODUCT = '@SC/REMOVE_PRODUCT';
export const CHANGE_PRODUCT_QUANTITY = '@SC/CHANGE_PRODUCT_QUANTITY';
export const UPDATE_CART = '@SC/UPDATE_CART';
